"""add returned order status

Revision ID: 7ba1dab358af
Revises: 4cc2c7a90669
Create Date: 2026-09-02 16:18:17.687111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7ba1dab358af'
down_revision: Union[str, Sequence[str], None] = '4cc2c7a90669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###