"""add stripe payment ids and webhook events

Revision ID: 946aace77274
Revises: 7ba1dab358af
Create Date: 2026-09-03 16:30:06.667133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '946aace77274'
down_revision: Union[str, Sequence[str], None] = '7ba1dab358af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('stripe_session_id', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True))
    op.drop_index(op.f('transaction_id'), table_name='payments')
    op.create_index(op.f('ix_payments_stripe_payment_intent_id'), 'payments', ['stripe_payment_intent_id'], unique=True)
    op.create_index(op.f('ix_payments_stripe_session_id'), 'payments', ['stripe_session_id'], unique=True)
    op.drop_column('payments', 'transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('transaction_id', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_payments_stripe_session_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_stripe_payment_intent_id'), table_name='payments')
    op.create_index(op.f('transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.drop_column('payments', 'stripe_payment_intent_id')
    op.drop_column('payments', 'stripe_session_id')
    # ### end Alembic commands ###